#!/bin/bash
# postBuild: Installiere zusätzliche Pakete

# Damit Voilà im Binder funktioniert:
jupyter server extension enable voila --sys-prefix

# Optional: weitere Befehle wie db-Migration, Assets kopieren etc.
