#!/bin/bash
# postBuild: Installiere zusätzliche Pakete

chmod +x start

# Damit Voilà im Binder funktioniert:
jupyter server extension enable voila --sys-prefix

# Optional: weitere Befehle wie db-Migration, Assets kopieren etc.
